#!/bin/bash
# Fail2ban Configuration Script for WallStreetSim
# This script installs and configures fail2ban for SSH protection
#
# Usage: sudo ./scripts/configure-fail2ban.sh [--dry-run] [--uninstall]
#
# Options:
#   --dry-run     Show what would be done without making changes
#   --uninstall   Remove fail2ban configuration (keeps package installed)
#
# Configuration:
#   - SSH jail enabled with aggressive settings
#   - Ban time: 1 hour (increases with repeat offenders)
#   - Find time: 10 minutes (window for counting failures)
#   - Max retry: 5 attempts before ban
#   - Ignores localhost and private networks

set -euo pipefail

# Configuration
readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly JAIL_LOCAL="/etc/fail2ban/jail.local"
readonly JAIL_D_DIR="/etc/fail2ban/jail.d"
readonly SSH_JAIL_CONF="$JAIL_D_DIR/sshd.local"

# Fail2ban settings
readonly BAN_TIME="1h"           # Ban duration (1 hour)
readonly FIND_TIME="10m"         # Time window for counting failures
readonly MAX_RETRY=5             # Max failures before ban
readonly BAN_TIME_INCREMENT="1h" # Additional time for repeat offenders
readonly BAN_TIME_MULTIPLIERS="1 2 4 8 16 32"  # Multipliers for repeat bans

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Flags
DRY_RUN=false
UNINSTALL=false

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Parse command line arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                DRY_RUN=true
                log_info "Dry run mode enabled - no changes will be made"
                shift
                ;;
            --uninstall)
                UNINSTALL=true
                log_warning "Uninstall mode enabled - will remove fail2ban configuration"
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done
}

show_help() {
    cat << EOF
Usage: sudo $SCRIPT_NAME [OPTIONS]

Configure fail2ban for SSH protection on WallStreetSim VPS.

Options:
    --dry-run     Show what would be done without making changes
    --uninstall   Remove fail2ban configuration (keeps package installed)
    -h, --help    Show this help message

Configuration details:
    Ban time:     $BAN_TIME (increases with repeat offenders)
    Find time:    $FIND_TIME (window for counting failures)
    Max retry:    $MAX_RETRY attempts before ban

Whitelisted:
    - 127.0.0.0/8  (localhost)
    - 10.0.0.0/8   (private network)
    - 172.16.0.0/12 (private network)
    - 192.168.0.0/16 (private network)

Examples:
    sudo $SCRIPT_NAME              # Install and configure fail2ban
    sudo $SCRIPT_NAME --dry-run    # Preview changes
    sudo $SCRIPT_NAME --uninstall  # Remove configuration

Useful commands after installation:
    sudo fail2ban-client status           # Show jail status
    sudo fail2ban-client status sshd      # Show SSH jail details
    sudo fail2ban-client set sshd unbanip IP  # Unban an IP
    sudo tail -f /var/log/fail2ban.log    # Watch fail2ban logs

EOF
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Check if fail2ban is installed
check_fail2ban_installed() {
    if command -v fail2ban-client &> /dev/null; then
        log_info "fail2ban is installed"
        return 0
    else
        return 1
    fi
}

# Install fail2ban
install_fail2ban() {
    log_info "Installing fail2ban..."
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would execute: apt-get update && apt-get install -y fail2ban"
    else
        apt-get update
        apt-get install -y fail2ban
    fi
    log_success "fail2ban installed"
}

# Create jail.local configuration
create_jail_local() {
    log_info "Creating $JAIL_LOCAL..."

    local config_content
    config_content=$(cat << 'JAILEOF'
# Fail2ban local configuration for WallStreetSim
# This file overrides /etc/fail2ban/jail.conf
# Generated by configure-fail2ban.sh

[DEFAULT]
# Ignore localhost and private networks
ignoreip = 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16

# Ban settings
bantime = 1h
findtime = 10m
maxretry = 5

# Ban time increases for repeat offenders
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 1w

# Use systemd backend for log reading
backend = systemd

# Email notifications (disabled by default)
# destemail = admin@example.com
# sender = fail2ban@example.com
# mta = sendmail
# action = %(action_mwl)s

# Default action: ban only (no email)
action = %(action_)s

JAILEOF
)

    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would create $JAIL_LOCAL with content:"
        echo "---"
        echo "$config_content"
        echo "---"
    else
        echo "$config_content" > "$JAIL_LOCAL"
        chmod 644 "$JAIL_LOCAL"
    fi
    log_success "Created $JAIL_LOCAL"
}

# Create SSH jail configuration
create_ssh_jail() {
    log_info "Creating SSH jail configuration..."

    # Ensure jail.d directory exists
    if [[ "$DRY_RUN" != true ]]; then
        mkdir -p "$JAIL_D_DIR"
    fi

    local ssh_config
    ssh_config=$(cat << 'SSHEOF'
# SSH jail configuration for WallStreetSim
# Protects against brute force SSH attacks
# Generated by configure-fail2ban.sh

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = %(sshd_log)s
backend = %(sshd_backend)s

# Override defaults for SSH - more strict
maxretry = 5
findtime = 10m
bantime = 1h

# Ban time multiplier for repeat offenders
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 1w

SSHEOF
)

    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would create $SSH_JAIL_CONF with content:"
        echo "---"
        echo "$ssh_config"
        echo "---"
    else
        echo "$ssh_config" > "$SSH_JAIL_CONF"
        chmod 644 "$SSH_JAIL_CONF"
    fi
    log_success "Created $SSH_JAIL_CONF"
}

# Enable and start fail2ban service
enable_fail2ban_service() {
    log_info "Enabling and starting fail2ban service..."
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would execute: systemctl enable fail2ban"
        log_info "[DRY RUN] Would execute: systemctl restart fail2ban"
    else
        systemctl enable fail2ban
        systemctl restart fail2ban
    fi
    log_success "fail2ban service enabled and started"
}

# Show fail2ban status
show_status() {
    log_info "Fail2ban status:"
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would show: fail2ban-client status"
        fail2ban-client status 2>/dev/null || log_info "fail2ban not running (expected in dry run)"
    else
        fail2ban-client status || true
        echo ""
        log_info "SSH jail status:"
        fail2ban-client status sshd || true
    fi
}

# Uninstall fail2ban configuration
uninstall_config() {
    log_info "Removing fail2ban configuration..."

    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would remove: $SSH_JAIL_CONF"
        log_info "[DRY RUN] Would remove: $JAIL_LOCAL"
        log_info "[DRY RUN] Would execute: systemctl restart fail2ban"
    else
        # Remove configuration files
        if [[ -f "$SSH_JAIL_CONF" ]]; then
            rm -f "$SSH_JAIL_CONF"
            log_success "Removed $SSH_JAIL_CONF"
        fi

        if [[ -f "$JAIL_LOCAL" ]]; then
            rm -f "$JAIL_LOCAL"
            log_success "Removed $JAIL_LOCAL"
        fi

        # Restart fail2ban to apply changes
        if systemctl is-active --quiet fail2ban; then
            systemctl restart fail2ban
            log_success "Restarted fail2ban service"
        fi
    fi

    log_success "fail2ban configuration removed"
    log_info "Note: fail2ban package is still installed. To remove completely:"
    log_info "  sudo apt-get remove --purge fail2ban"
}

# Verify configuration
verify_config() {
    log_info "Verifying fail2ban configuration..."
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would verify configuration syntax"
    else
        if fail2ban-client -t &> /dev/null; then
            log_success "Configuration syntax is valid"
        else
            log_error "Configuration syntax error detected"
            fail2ban-client -t
            exit 1
        fi
    fi
}

# Main function
main() {
    echo "========================================"
    echo "  WallStreetSim Fail2ban Configuration"
    echo "========================================"
    echo ""

    parse_args "$@"

    # Skip root check in dry-run mode for testing
    if [[ "$DRY_RUN" != true ]]; then
        check_root
    fi

    if [[ "$UNINSTALL" == true ]]; then
        uninstall_config
        exit 0
    fi

    # Install fail2ban if not present
    if ! check_fail2ban_installed; then
        install_fail2ban
    fi

    # Create configuration files
    create_jail_local
    create_ssh_jail

    # Verify configuration
    verify_config

    # Enable and start service
    enable_fail2ban_service

    echo ""
    echo "========================================"
    show_status
    echo "========================================"

    log_success "Fail2ban configuration complete!"
    echo ""
    log_info "Useful commands:"
    log_info "  sudo fail2ban-client status sshd      # Check SSH jail status"
    log_info "  sudo fail2ban-client set sshd unbanip IP  # Unban an IP"
    log_info "  sudo tail -f /var/log/fail2ban.log    # Watch logs"
}

# Run main function
main "$@"
